### ISSUE TITLE
Optionally specify to search in a specific relay

### ISSUE THREAD

**Issue by cxplay** [SamSamskies/advancednostrsearch#17]
I have a relay that only holds notes for me and my friends, and I would like to be able to search our notes through this relay. Occasionally I also use it to find out if certain relays hold my notes. So I'd like to have support for searching for notes from a specific relay or relays.

**Comment by SamSamskies** [comment]
Does your relay support [nip-50](https://github.com/nostr-protocol/nips/blob/master/50.md)? It won't work if it doesn't. If it does, can you send me the URI so that I can test it? You can [DM it to me](https://njump.me/npub1vp8fdcyejd4pqjyrjk9sgz68vuhq7pyvnzk8j0ehlljvwgp8n6eqsrnpsw) if you don't want other people to know the URI.

**Comment by SamSamskies** [comment]
There are not many relays that support nip-50. That's why I haven't added an option to select a relay. Also, I'm trying to keep the UI simple.

**Comment by cxplay** [comment]
I see, thanks for the explanation, looks like my relay software doesn't support it. Sorry.
